*KEYWORD
*ICFD_CONTROL_IMPOSED_MOVE
$#     pid    lcidvx    lcidvy    lcidvz    
         0         0         0         1 
*DEFINE_CURVE_TITLE
Velocity imposed
$#    lcid      sidr       sfa       sfo      offa      offo    dattyp
        1              
$#                a1                  o1				
$---+----1----+----2----+----3----+----4--
0                          0.5
3                          0.5
*END

